# Generated by Django 3.2.6 on 2021-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='tag_level_sum',
            field=models.FloatField(default=1, verbose_name='Сумма соответствия тегов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='perks',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.Perk'),
        ),
        migrations.AlterField(
            model_name='tagperk',
            name='level',
            field=models.FloatField(verbose_name='Соответствие'),
        ),
    ]
