# Generated by Django 3.2.6 on 2021-08-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('kpi', models.IntegerField(verbose_name='Общая эффективность')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='department.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectivity', models.IntegerField(verbose_name='Эффективность')),
                ('abilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'способность пользователя',
                'verbose_name_plural': 'способности пользователя',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='specializations',
            field=models.ManyToManyField(related_name='users', through='user.UserSpecialization', to='core.Specialization'),
        ),
    ]
