# Generated by Django 3.2.6 on 2021-08-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='department.department', verbose_name='Родительский департамент')),
            ],
            options={
                'verbose_name': 'департамент',
                'verbose_name_plural': 'департаменты',
            },
        ),
    ]
